mustache
mustacheRoot

	^ '<div class="row">
	<div class="col-md-8 col-md-offset-2">
	<h2>Renraku Server</h2>
	<p>This is a server for a Pharo quality framework called Renraku. You can probably read more about it on <a href="https://github.com/Uko/Renraku">GitHub</a>.
So far we have collected {{ complaints }} feedbacks(s) about SmallLint critics. To see a short summary please proceed to the <a href="/rules">rules page</a>.</p>
</div>
</div>' 